language: ruby
rvm:
  - 2.5.3
cache: bundler
script:
  - gem update --system
  - gem install bundler -v "$(grep -A 1 "BUNDLED WITH" Gemfile.lock | tail -n 1)"
  - bundle exec rake db:drop db:create db:migrate db:seed
  - bundle exec rake spec
before_install:
  - cat config/database.yml.travis > config/database.yml
  - cat config/couchdb.yml.travis > config/couchdb.yml
services:
  - mysql
  - couchdb
